# build according provided Dockerfile
a1:
  build: .
  privileged: true
  net: etcd-functional
  ports:
    - "10001:9027"
a2:
  build: .
  privileged: true
  net: etcd-functional
  ports:
    - "10002:9027"
a3:
  build: .
  privileged: true
  net: etcd-functional
  ports:
    - "10003:9027"
tester:
  build: .
  privileged: true
  net: etcd-functional
  ports:
    - "10004:9028"
  command:
    - /etcd-tester
    - -agent-endpoints
    - "172.20.0.2:9027,172.20.0.3:9027,172.20.0.4:9027"
    # - -limit
    # - "1"
    - -stress-key-count
    - "1"
    - -stress-key-size
    - "1"
    - -failures
    - ""
    - -external-failures
    - "/dummy.sh"
